# Generated by Django 3.1 on 2020-08-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200819_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_dimensions',
        ),
    ]
