# Generated by Django 3.1 on 2020-08-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_carousel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='CarouselImage',
        ),
    ]
