# Generated by Django 3.1 on 2020-08-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200819_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='product',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', to_field='sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
